### ISSUE TITLE
Arbitrum "Permissionless" and "Force TX mechanism" descriptions

### ISSUE THREAD

**Issue by DZGoldman** [l2beat/l2beat#107]
The key here is that for both of these, the sequencer can be avoided entirely.
I.e., Force TX mechanism currently reads

- "Sequencer can be forced to append a txn to the rollup"
This actually isn't true, but there is a force tx mechanism; a user posts their transaction directly on chain, and eventually it will be made available for validators to include in assertions (no sequencer involvement).

Likewise, permissionless reads 
- "Only the sequencer can produce blocks
Any body can be a validator and make assertions (i.e., propose state updates to Arbitrum). The Sequencer only has a special privilege to propose fast soft-confirmed updates before things hit the L1 (i.e., before an assertion is made). I think I'd argue that this effectively makes Arbitrum itself a "Permissionless? Yes", tho this is debatable, since the sequencer itself is a permissioned entity.     

(As I've said elsewhere, this is by far the best L2 tracker I've seen — thanks for putting it together!)

**Comment by sz-piotr** [comment]
Thanks for the issue. We are currently in the process of building a new version of the website that will correct mistakes in the current version. We have not ported back our research, because the data will be presented differently to the current key-value pair approach.

I have compared your findings with our current research and updated the Arbitrum entry to match reality.
